#Configuration file used in DEVELOPEMENT. 
## NOTE: if you get this error: 
# Near line 0 (last key parsed ''): bare keys cannot contain '\ufeff'
# It is because this config.toml file is saved with BOM. Notepad does it, please use "save as.." with UTF-8 without BOM.

# used to develop on windows for alarm view
ServiceURL = "127.0.0.1:5589" 
RootURLPattern = "/iot/"
DebugVerbose = false
VueLibName = "vue.js"
TokenFilename = "token.json"
UseTLS = false

[Influx]
BucketName = "iotair"
DbHost = "http://localhost:8086"
Org = "invido"

[SQLite]
DBPath = "../Db/test-iotinvido.db"