# configuration for iot-invido
ServiceURL = "127.0.0.1:5589" 
RootURLPattern = "/" # on target,  keep in main for the proxy
DebugVerbose = false
VueLibName = "vue_prod.js"
TokenFilename = "token.json"
UseTLS = false

[Influx]
BucketName = "iotair"
DbHost = "http://localhost:8086"
Org = "invido"


